name: CosmeticsPlugin
version: 1.0-SNAPSHOT
main: com.Aleksy23.CosmeticsPlugin
author: Aleksy23
description: Plugin adding cosmetics to the game.
api-version: 1.13

commands:
  cosmetics:
    description: Opens cosmetics menu.
    usage: /cosmetics
    permission: cosmeticsplugin.use
    permission-message: You don't have permission to use this command!
  petname:
    description: Names your pet
    usage: /petname <name>
    aliases: [nazwapet, pname]