name: CosmeticsPlugin
version: 1.0-SNAPSHOT
main: com.Aleksy23.CosmeticsPlugin # Pełna ścieżka do Twojej głównej klasy
author: Aleksy23 # Możesz tu wpisać swój nick
description: Plugin dodajacy kosmetyki do gry.
api-version: 1.13 # To informuje Spigota o kompatybilności API. Dla 1.8 możesz zostawić 1.13 lub użyć 1.8.

commands:
  cosmetics: # Nazwa komendy, którą gracze będą wpisywać (np. /cosmetics)
    description: Otwiera menu z kosmetykami.
    usage: /Cosmetics
    permission: cosmeticsplugin.use # Opcjonalne: uprawnienie wymagane do użycia komendy
    permission-message: Nie masz uprawnien do uzycia tej komendy!